### PR TITLE
fix: [SIW-1679] Restore optional parameter to get all disclosures

### PR DESCRIPTION
**Pull request by gispada**
#### List of Changes

- Pass `includeUndefinedAttributes` to `parseCredentialSdJwt`.

#### Motivation and Context

Currently it is possible to pass `includeUndefinedAttributes` to `verifyAndParseCredential`, but that parameter is lost in the internal function invocations, so it is not possible to get disclosures/claims that are not explicitly supported in the entity configuration.

### CODE REVIEW

**Review by LazyAfternoons — CHANGES_REQUESTED** [review]
Should we update the function documentation with this new parameter and possibly also `ignoreMissingAttributes` which seems missing? I'd also add a note which specifies that they must be false in production.

**Comment by gispada** [comment]
I have improved the documentation in cf2e9167800857caf3deb992a600e4a5c4557786.

**Comment by LazyAfternoons** [comment]
> I have improved the documentation in [cf2e916](https://github.com/pagopa/io-react-native-wallet/commit/cf2e9167800857caf3deb992a600e4a5c4557786).

Good job, I'd also add it to the parameters of `verifyAndParseCredential`, something like: 
```
/**
 * Verify and parse an encoded credential.
...
 * @param context.ignoreMissingAttributes ...
 * @param context.includeUndefinedAttributes ...
...
 */
 ```
 
 Does it make sense to you?

**Comment by gispada** [comment]
Updated `verifyAndParseCredential` JSDoc  in d2fc59c037f3acceef92daa736eff0f0c78253eb.

**Review by LazyAfternoons — APPROVED** [review]
LGTM

**Pull request merged**
